# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'design_correios_janela2.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Janela2(object):
    def setupUi(self, Janela2):
        Janela2.setObjectName("Janela2")
        Janela2.resize(439, 294)
        Janela2.setStyleSheet("background-color: rgb(255, 255, 0);")
        self.centralwidget = QtWidgets.QWidget(Janela2)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 0, 431, 141))
        self.label.setStyleSheet("font: 87 14pt \"Arial Black\";")
        self.label.setObjectName("label")
        self.inputCodigoMercadoria = QtWidgets.QLineEdit(self.centralwidget)
        self.inputCodigoMercadoria.setGeometry(QtCore.QRect(150, 110, 281, 31))
        self.inputCodigoMercadoria.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.inputCodigoMercadoria.setObjectName("inputCodigoMercadoria")
        self.buttonSalvarNome = QtWidgets.QPushButton(self.centralwidget)
        self.buttonSalvarNome.setGeometry(QtCore.QRect(160, 220, 141, 71))
        self.buttonSalvarNome.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"font: 12pt \"MS Shell Dlg 2\";")
        self.buttonSalvarNome.setObjectName("buttonSalvarNome")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(20, 120, 121, 16))
        self.label_2.setObjectName("label_2")
        self.inputNomeMercadoria = QtWidgets.QLineEdit(self.centralwidget)
        self.inputNomeMercadoria.setGeometry(QtCore.QRect(150, 160, 281, 31))
        self.inputNomeMercadoria.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.inputNomeMercadoria.setObjectName("inputNomeMercadoria")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(10, 170, 131, 20))
        self.label_3.setObjectName("label_3")
        Janela2.setCentralWidget(self.centralwidget)

        self.retranslateUi(Janela2)
        QtCore.QMetaObject.connectSlotsByName(Janela2)

    def retranslateUi(self, Janela2):
        _translate = QtCore.QCoreApplication.translate
        Janela2.setWindowTitle(_translate("Janela2", "MainWindow"))
        self.label.setText(_translate("Janela2", "Coloque; Código e Nome da mercadoria"))
        self.buttonSalvarNome.setText(_translate("Janela2", "SALVAR"))
        self.label_2.setText(_translate("Janela2", "CODIGO DE RASTREIO:"))
        self.label_3.setText(_translate("Janela2", "NOME DA MERCADORIA:"))
