# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'design_correios.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(666, 490)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.inputCodigo = QtWidgets.QLineEdit(self.centralwidget)
        self.inputCodigo.setGeometry(QtCore.QRect(9, 10, 551, 20))
        self.inputCodigo.setObjectName("inputCodigo")
        self.button_salvar = QtWidgets.QPushButton(self.centralwidget)
        self.button_salvar.setGeometry(QtCore.QRect(567, 9, 90, 23))
        self.button_salvar.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.button_salvar.setStyleSheet("border-color: rgb(255, 0, 0);\n"
"background-color: rgb(85, 170, 255);")
        self.button_salvar.setObjectName("button_salvar")
        self.button_rastreio = QtWidgets.QPushButton(self.centralwidget)
        self.button_rastreio.setGeometry(QtCore.QRect(9, 38, 551, 23))
        self.button_rastreio.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.button_rastreio.setStyleSheet("border-color: rgb(0, 255, 0);\n"
"background-color: rgb(255, 255, 10);\n"
"gridline-color: rgb(0, 38, 255);\n"
"gridline-color: rgb(85, 255, 0);")
        self.button_rastreio.setObjectName("button_rastreio")
        self.label_tittle = QtWidgets.QLabel(self.centralwidget)
        self.label_tittle.setGeometry(QtCore.QRect(0, 300, 321, 191))
        self.label_tittle.setMinimumSize(QtCore.QSize(60, 30))
        self.label_tittle.setMaximumSize(QtCore.QSize(800, 600))
        self.label_tittle.setBaseSize(QtCore.QSize(360, 250))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(22)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(10)
        self.label_tittle.setFont(font)
        self.label_tittle.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.label_tittle.setStyleSheet("background-color: rgb(255, 255, 0);\n"
"font: 87 22pt \"Arial Black\";")
        self.label_tittle.setObjectName("label_tittle")
        self.scrollArea = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea.setGeometry(QtCore.QRect(320, 300, 341, 191))
        self.scrollArea.setAutoFillBackground(False)
        self.scrollArea.setStyleSheet("background-color: rgb(0, 144, 216);")
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 339, 189))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.box_codigos = QtWidgets.QComboBox(self.scrollAreaWidgetContents)
        self.box_codigos.setGeometry(QtCore.QRect(50, 70, 251, 41))
        self.box_codigos.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.box_codigos.setObjectName("box_codigos")
        self.buttonBoxCodigos = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.buttonBoxCodigos.setGeometry(QtCore.QRect(140, 120, 75, 31))
        self.buttonBoxCodigos.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.buttonBoxCodigos.setObjectName("buttonBoxCodigos")
        self.clearList = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.clearList.setGeometry(QtCore.QRect(44, 160, 261, 23))
        self.clearList.setStyleSheet("background-color: rgb(255, 170, 0);")
        self.clearList.setObjectName("clearList")
        self.attList = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.attList.setGeometry(QtCore.QRect(50, 35, 251, 31))
        self.attList.setStyleSheet("background-color: rgb(255, 255, 0);")
        self.attList.setObjectName("attList")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.area_dados = QtWidgets.QScrollArea(self.centralwidget)
        self.area_dados.setGeometry(QtCore.QRect(-1, 67, 671, 231))
        self.area_dados.setStyleSheet("background-color: rgb(166, 166, 166);")
        self.area_dados.setWidgetResizable(True)
        self.area_dados.setObjectName("area_dados")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 669, 229))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.gridLayout = QtWidgets.QGridLayout(self.scrollAreaWidgetContents_2)
        self.gridLayout.setObjectName("gridLayout")
        self.label_dosDados = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(12)
        self.label_dosDados.setFont(font)
        self.label_dosDados.setText("")
        self.label_dosDados.setObjectName("label_dosDados")
        self.gridLayout.addWidget(self.label_dosDados, 0, 0, 1, 1)
        self.area_dados.setWidget(self.scrollAreaWidgetContents_2)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Correios Tracker by.Leandro Furtado"))
        self.inputCodigo.setText(_translate("MainWindow", "Digite aqui o código da sua mercadoria"))
        self.button_salvar.setText(_translate("MainWindow", "SALVAR CÓDIGO"))
        self.button_rastreio.setText(_translate("MainWindow", "RASTREAR MERCADORIA"))
        self.label_tittle.setText(_translate("MainWindow", " CÓDIGOS SALVOS:"))
        self.buttonBoxCodigos.setText(_translate("MainWindow", "SELECIONAR"))
        self.clearList.setText(_translate("MainWindow", "LIMPAR LISTA(feche para funcionar)"))
        self.attList.setText(_translate("MainWindow", "ATUALIZAR LISTA"))
